install.packages('tidyverse')

install.packages("downloader")

require(downloader)
library(readxl)
t1 <-read_excel("new_england_patriots_madden_nfl_11.xls")
t2 <-read_excel("philadelphia_eagles_madden_nfl_11.xls")
t3 <-read_excel("pittsburgh_steelers_madden_nfl_11.xls")
t4 <-read_excel("st._louis_rams_madden_nfl_11.xls")
t5 <-read_excel("baltimore_ravens_madden_nfl_11.xls")
t6 <-read_excel("tennessee_titans_madden_nfl_11.xls")
t7 <-read_excel("jacksonville_jaguars_madden_nfl_11.xls")
t8 <-read_excel("cleveland_browns_madden_nfl_11.xls")
t9 <-read_excel("cincinnati_bengals_madden_nfl_11.xls")
t10<-read_excel("new_york_jets_madden_nfl_11.xls")
t11<-read_excel("indianapolis_colts_madden_nfl_11.xls")
t12<-read_excel("miami_dolphins_madden_nfl_11.xls")
t13<-read_excel("san_francisco_49ers_madden_nfl_11.xls")
t14<-read_excel("buffalo_bills_madden_nfl_11.xls")
t15<-read_excel("new_orleans_saints_madden_nfl_11.xls")
t16<-read_excel("denver_broncos_madden_nfl_11.xls")
t17<-read_excel("oakland_raiders_madden_nfl_11.xls")
t18<-read_excel("seattle_seahawks_madden_nfl_11.xls")
t19<-read_excel("san_diego_chargers_madden_nfl_11.xls")
t20<-read_excel("kansas_city_chiefs_madden_nfl_11.xls")
t21<-read_excel("tampa_bay_buccaneers_madden_nfl_11.xls")
t22<-read_excel("detroit_lions_madden_nfl_11.xls")
t23<-read_excel("green_bay_packers_madden_nfl_11.xls")
t24<-read_excel("minnesota_vikings_madden_nfl_11.xls")
t25<-read_excel("chicago_bears_madden_nfl_11.xls")
t26<-read_excel("new_york_giants_madden_nfl_11.xls")
t27<-read_excel("washington_redskins_madden_nfl_11.xls")
t28<-read_excel("dallas_cowboys_madden_nfl_11.xls")
t29<-read_excel("arizona_cardinals_madden_nfl_11.xls")
t30<-read_excel("atlanta_falcons_madden_nfl_11.xls")
t31<-read_excel("carolina_panthers_madden_nfl_11.xls")
t32<-read_excel("tennessee_titans_madden_nfl_11.xls")



matriz <- matrix(c(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32),ncol = 32, nrow=1)
linha = 1
require(downloader)
while(linha<=length(matriz)){
  download(paste("https://maddenratings.weebly.com/uploads/1/4/0/9/14097292/", matriz[linha], sep=""), matriz[linha], mode = "wb")
  linha<-linha+1
}
  

t1["champ"]<-c("0")
t2["champ"]<-c("0")
t3["champ"]<-c("0")
t4["champ"]<-c("0")
t5["champ"]<-c("0")
t6["champ"]<-c("0")
t7["champ"]<-c("0")
t8["champ"]<-c("0")
t9["champ"]<-c("0")
t10["champ"]<-c("0")
t11["champ"]<-c("0")
t12["champ"]<-c("0")
t13["champ"]<-c("0")
t14["champ"]<-c("0")
t15["champ"]<-c("0")
t16["champ"]<-c("0")
t17["champ"]<-c("0")
t18["champ"]<-c("0")
t19["champ"]<-c("0")
t20["champ"]<-c("0")
t21["champ"]<-c("0")
t22["champ"]<-c("0")
t23["champ"]<-c("1")
t24["champ"]<-c("0")
t25["champ"]<-c("0")
t26["champ"]<-c("0")
t27["champ"]<-c("0")
t28["champ"]<-c("0")
t29["champ"]<-c("0")
t30["champ"]<-c("0")
t31["champ"]<-c("0")
t32["champ"]<-c("0")

install.packages('plyr')


install.packages('dplyr')
library('dplyr')
resultado <- t1%>%full_join(t2)%>%full_join(t3)%>%full_join(t4)%>%full_join(t5)%>%full_join(t6)%>%full_join(t7)%>%full_join(t8)%>%full_join(t9)%>%full_join(t10)%>%full_join(t11)%>%full_join(t12)%>%full_join(t13)%>%full_join(t14)%>%full_join(t15)%>%full_join(t16)%>%full_join(t17)%>%full_join(t18)%>%full_join(t19)%>%full_join(t20)%>%full_join(t21)%>%full_join(t22)%>%full_join(t23)%>%full_join(t25)%>%full_join(t26)%>%full_join(t27)%>%full_join(t28)%>%full_join(t29)%>%full_join(t30)%>%full_join(t32)%>%full_join(t31)%>%full_join(t24)

View(resultado)

install.packages('openxlsx')
library('openxlsx')
write.xls(resultado, '2010.xls')